version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                command: |
                    apt-get install openslide-tools -y sudo
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install -U pytest
            - run:
                command: |
                    . venv/bin/activate
                    cd test
                    pytest .
